allowBuilds:
  '@parcel/watcher': true
minimumReleaseAgeExclude:
  - '@fluentui/react-icons@2.0.329'
  - '@typescript-eslint/eslint-plugin@8.61.0'
  - '@typescript-eslint/parser@8.61.0'
  - '@typescript-eslint/project-service@8.61.0'
  - '@typescript-eslint/scope-manager@8.61.0'
  - '@typescript-eslint/tsconfig-utils@8.61.0'
  - '@typescript-eslint/type-utils@8.61.0'
  - '@typescript-eslint/types@8.61.0'
  - '@typescript-eslint/typescript-estree@8.61.0'
  - '@typescript-eslint/utils@8.61.0'
  - '@typescript-eslint/visitor-keys@8.61.0'
